name: MineGames
main : de.linzn.minegames.MineGames
version: ${project.version}
description: MineGaming Survival Games
author: Niklas Linz
depend: [WorldEdit, Vault]
api-version: 1.13

commands:
  minegames:
    description: Plugin command
    aliases: [mg, sg, hg]

permissions:
    mg.player.all:
        default: op
        description: MineGames Player Commands
        children:
            mg.player.play: true
            mg.player.vote: true
            mg.player.spectate: true
            mg.player.joinlobby: true
            mg.player.listarenas: true
    mg.player.play:
        description: Allows the user to click a sign to join a game.
        default: op
    mg.player.vote:
        description: Allows the user to vote to start a game.
        default: op
    mg.player.spectate:
        description:  Allows the user to spectate a game.
        default: op
    mg.player.joinlobby:
        description: Allows the use of /sg join to join the lobby.
        default: op
    mg.player.listarenas:
        description: List all arenas set up.
        default: op
    mg.player.list:
        description: List all players in the arena you are playing in.
        default: op
    mg.staff.all:
        default: op
        description: MineGames Staff Commands
        children:
            mg.player.all: true
            mg.staff.forcestart: true
            mg.staff.disablearena: true
            mg.staff.enablearena: true
            mg.staff.nocmdblock: true
            mg.staff.reset: true
            mg.staff.refill: true
            mg.staff.teleport: true
    mg.staff.forcestart:
        description: Allows the user to force start a game.
        default: op
    mg.staff.disablearena:
        description: Allows the user to disable an arena.
        default: op
    mg.staff.enablearena:
        description: Allows the user to enable an arena.
        default: op
    mg.staff.nocmdblock:
        description: Allows user to bypass in-game command block.
        default: op
    mg.admin.all:
        default: op
        description: MineGames Admin Commands
        children:
            mg.staff.all: true
            mg.admin.createarena: true
            mg.admin.setarenaspawns: true
            mg.admin.resetspawns: true
            mg.admin.deletearena: true
            mg.admin.setlobby: true
            mg.admin.flag: true
            mg.admin.addwall: true
            mg.admin.reload: true
    mg.admin.createarena:
        description: Allows the user to create an arena.
        default: op
    mg.admin.setarenaspawns:
        description: Allows user to set arena spawns.
        default: op
    mg.admin.resetspawns:
        description: Allows the user to reset all spawnpoints.
        default: op
    mg.admin.deletearena:
        description: Allows a user to delete an arena.
        default: op
    mg.admin.setlobby:
        description: Allows the user to set the lobby spawn and wall.
        default: op
    mg.admin.flag:
        description: Allows the user to modify per-arena flags.
        default: op
    mg.admin.addwall:
        description: Allows the user to modify per-arena flags.
        default: op
    mg.admin.reload:
        description: .
        default: op
    mg.staff.reset:
        description: .
        default: op
    mg.staff.refill:
        description: .
        default: op
    mg.staff.teleport:
        description: .
        default: op